{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "from skimage.transform import rescale, resize\n",
    "from skimage.filters import gaussian\n",
    "from cellpose import models\n",
    "import torch\n",
    "import tifffile\n",
    "import nd2\n",
    "\n",
    "import napari"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "viewer = napari.Viewer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "if sys.platform == 'darwin':\n",
    "    d = torch.device('mps')\n",
    "    model = models.Cellpose(gpu=False, device=d, model_type='cyto2')\n",
    "else:\n",
    "    # change gpu=True if on windows, and get rid of device\n",
    "    model = models.Cellpose(gpu=True, model_type='cyto2')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### nd2 files\n",
    "We will be using a Nikon file for this notebook, using the `nd2` package. The `nd2` package has an imread function like skimage and tifffile:\n",
    "\n",
    "```python\n",
    "data = nd2.imread(filename)\n",
    "```\n",
    "\n",
    "Instead, we will use the `ND2File` object gives us access to the metadata (like x, y, z scaling, excitation wavelengths, etc.) that we will need.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(40, 3, 2044, 2048)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "imagefile = 'Data/WT003.nd2'\n",
    "\n",
    "### create the file object - this doesn't read the image array data\n",
    "nd2file = nd2.ND2File(imagefile)\n",
    "image = nd2file.asarray()\n",
    "image.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Add the image to the napari viewer. From the shape output in the last cell, the channel axis is 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<Image layer 'Image' at 0x2d723fac0>,\n",
       " <Image layer 'Image [1]' at 0x2c42af700>,\n",
       " <Image layer 'Image [2]' at 0x2d7c9dd50>]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "viewer.add_image(image, channel_axis=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Rotate the image in 3D and notice the 3D scaling is not set. To get the right values for the z scaling we need to look at the metadata.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Metadata\n",
    "\n",
    "Exlpore what is inside the metadata variable of the nd2file object"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "nd2file.metadata.channel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(0.065, 0.065, 0.3, 0.21666666666666667)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "md1 = nd2file.metadata.channels[1]\n",
    "xum, yum, zum = md1.volume.axesCalibration\n",
    "zscale = xum/zum\n",
    "xum, yum, zum, zscale"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Changing the layer scale\n",
    "\n",
    "Use a for loop to change the scale of each layer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "for y in viewer.layers:\n",
    "    y.scale = (1/zscale, 1, 1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Cellpose 3D\n",
    "\n",
    "Cellpose has a 3D option in `model.eval`, but it is not really 3D. It does the eval on every xy plane, then every yz plane, then every xz plane. After the eval cellpose reconstructs the results from each plane into 3D masks/labels.  For this to work the scaling in z needs to match the xy scaling. The `anisotropy` parameter can be used, and cellpose will adjust the input image. Another option is to rescale the image before using cellpose. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(40, 3, 443, 444)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "scaled = rescale(image, (1, 1, zscale, zscale), preserve_range=True)\n",
    "scaled = gaussian(scaled, sigma=(1, 0, 2, 2))\n",
    "scaled.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<Image layer 'Image' at 0x2cdec6e30>,\n",
       " <Image layer 'Image [1]' at 0x2cfafbf10>,\n",
       " <Image layer 'Image [2]' at 0x35d8bc940>]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "viewer.layers.clear()\n",
    "viewer.add_image(scaled, channel_axis=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "masks, _, _, _ = model.eval(scaled, diameter=75, do_3D=True, channels=[1,2],\n",
    "                            cellprob_threshold=1,\n",
    "                            flow_threshold=.3) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Labels layer 'masks' at 0x35dd87250>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 57 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 173 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 183 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 191 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 194 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 195 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 197 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 202 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 204 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 208 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 215 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 227 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 237 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 238 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 239 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 242 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 243 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 242 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 244 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 248 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 247 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 246 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 246 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 245 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 244 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 246 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 248 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 246 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 224 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 198 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 197 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 193 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 209 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 205 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 207 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 207 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 209 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 214 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 208 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 157 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 156 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 154 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 153 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 151 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 150 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 151 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 151 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 152 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 153 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 154 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 155 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 157 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 158 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 159 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 158 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 156 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 157 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 157 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 157 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 154 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 150 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 148 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 136 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 111 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 121 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 123 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 124 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 147 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 175 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 199 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 206 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 207 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 228 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 269 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 286 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 285 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 279 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 264 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 238 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 77 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 95 is out of bounds for axis 1 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 443 is out of bounds for axis 0 with size 443\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 177 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 188 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 190 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 190 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 192 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 196 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 196 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 196 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 196 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 194 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 193 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 192 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 193 is out of bounds for axis 2 with size 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 415, in _update_status_bar_from_cursor\n",
      "    self.status = active.get_status(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1391, in get_status\n",
      "    value = self.get_value(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1103, in get_value\n",
      "    value = self._get_value_3d(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1048, in _get_value_3d\n",
      "    self._get_value_ray(\n",
      "  File \"/Users/cjw/mambaforge/envs/py310/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 1016, in _get_value_ray\n",
      "    values = im_slice[tuple(clamped.T)]\n",
      "IndexError: index 443 is out of bounds for axis 0 with size 443\n"
     ]
    }
   ],
   "source": [
    "viewer.add_labels(masks)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "To use the cellpose results with the original image, the masks need to be scaled back to the original size. The `order` parameter is the key to making this successful.\n",
    "Settting `order=0` makes `resize` use nearest neighbors when upscaling an image rather than interpolation. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "shape = (image.shape[0], image.shape[2], image.shape[3])\n",
    "smasks = resize(masks, shape, order=0, preserve_range=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Labels layer 'smasks' at 0x2cfafb5b0>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "viewer.layers.clear()\n",
    "viewer.add_image(image, channel_axis=1)\n",
    "viewer.add_labels(smasks)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for y in viewer.layers:\n",
    "    y.scale = (1/zscale, 1, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(40, 2044, 2048)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "smasks.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "5.46963456"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "640*512*5564*3/1e9"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "py310",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
